SET search_path TO ardor;

CREATE TABLE SUPPLIERS(
	ID SERIAL2 NOT NULL,
	CODE VARCHAR(3) NOT NULL,
	SUPPLIER_NAME VARCHAR(100) NOT NULL,
	IS_ACTIVE BIT DEFAULT '1' NOT NULL,
	CREATED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
	MODIFIED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
	CONSTRAINT SUPPLIERS_PK PRIMARY KEY (ID),
	CONSTRAINT SUPPLIERS_UN UNIQUE (CODE)
);

CREATE INDEX SUPPLIERS_CODE_IDX ON SUPPLIERS(CODE,IS_ACTIVE);


CREATE TABLE LINK_SUPPLIER_BOOKING_TYPE(
	ID SERIAL2 NOT NULL,
	SUPPLIER_CODE VARCHAR(3) NOT NULL,
	BOOKING_TYPE_CODE VARCHAR(3) NOT NULL,
	IS_ACTIVE BIT DEFAULT '1' NOT NULL,
	CREATED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
	MODIFIED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
	CONSTRAINT LSBK_PK PRIMARY KEY (ID),
	CONSTRAINT LSBK_UN UNIQUE (SUPPLIER_CODE,BOOKING_TYPE_CODE),
	CONSTRAINT LSBK_SC_FK FOREIGN KEY(SUPPLIER_CODE) REFERENCES SUPPLIERS(CODE),
	CONSTRAINT LSBK_BTC_FK FOREIGN KEY(BOOKING_TYPE_CODE) REFERENCES M_BOOKING_TYPE(CODE)
);

CREATE INDEX LSBK_IDX ON LINK_SUPPLIER_BOOKING_TYPE(SUPPLIER_CODE,BOOKING_TYPE_CODE,IS_ACTIVE);

insert into SUPPLIERS (ID,CODE,SUPPLIER_NAME,IS_ACTIVE) VALUES ('1','HBD','HOTELBEDS','1');
insert into SUPPLIERS (ID,CODE,SUPPLIER_NAME,IS_ACTIVE) VALUES ('2','MND','MONDEE','1');

insert into LINK_SUPPLIER_BOOKING_TYPE (ID,SUPPLIER_CODE,BOOKING_TYPE_CODE,IS_ACTIVE) VALUES ('1','HBD','STY','1');
insert into LINK_SUPPLIER_BOOKING_TYPE (ID,SUPPLIER_CODE,BOOKING_TYPE_CODE,IS_ACTIVE) VALUES ('2','MND','AIR','1');
insert into LINK_SUPPLIER_BOOKING_TYPE (ID,SUPPLIER_CODE,BOOKING_TYPE_CODE,IS_ACTIVE) VALUES ('3','MND','STY','1');



