SET search_path TO ardor;


CREATE TABLE AIR_TRANS_HDR(
ID BIGSERIAL NOT NULL,
AIR_TRANS_ID VARCHAR(12) NOT NULL,
USER_CODE VARCHAR(20) NOT NULL,
CREATED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED_BY VARCHAR(20) NOT NULL,
FIRSTNAME VARCHAR(60),
LASTNAME VARCHAR(60),
EMAIL VARCHAR(100) NOT NULL,
PHONE VARCHAR(100) NOT NULL,
ADDRESS VARCHAR(1000),
TRANS_STATUS VARCHAR(3) NOT NULL,
QUOTED DECIMAL(18,2),
QUOTED_COST DECIMAL(18,2),
QUOTED_ADDITIONAL DECIMAL(18,2),
SUP_COST DECIMAL(18,2),
NET_COST DECIMAL(18,2),
NET_REMIT DECIMAL(18,2),
CHARGED DECIMAL(18,2),
REVENUE DECIMAL(18,2),
UNDER_CHARGE DECIMAL(18,2),
OVER_CHARGE DECIMAL(18,2),
MARKUP DECIMAL(18,2),
PROMOTION DECIMAL(18,2),
ADJUSTMENT DECIMAL(18,2),
CCFEE DECIMAL(18,2),
CUSTOMER_FOP VARCHAR(3),
SUPPLIER_FOP VARCHAR(3),
PAX VARCHAR(100),
TRANS_INFO VARCHAR(1500),
REMARKS VARCHAR(1500),
TRANS_IP VARCHAR(30),
TRANS_COUNTRY_CODE VARCHAR(3),
CONSTRAINT ATH_PK PRIMARY KEY (ID),
CONSTRAINT ATH_UN UNIQUE (AIR_TRANS_ID),
CONSTRAINT ATH_UC_FK FOREIGN KEY(USER_CODE) REFERENCES M_USER(USER_CODE),
CONSTRAINT ATH_MB_FK FOREIGN KEY(MODIFIED_BY) REFERENCES M_USER(USER_CODE)
);

CREATE INDEX ATH_IDX ON AIR_TRANS_HDR(AIR_TRANS_ID,USER_CODE,CREATED,TRANS_STATUS,TRANS_COUNTRY_CODE,EMAIL,PHONE);


CREATE TABLE AIR_TRANS_DTL(
ID BIGSERIAL NOT NULL,
AIR_TRANS_ID VARCHAR(12) NOT NULL,
AIR_TRANS_DTL_ID VARCHAR(20) NOT NULL,
BOOKING_TYPE VARCHAR(3) NOT NULL,
TRANS_TYPE VARCHAR(3) NOT NULL,
TRANS_STATUS VARCHAR(3) NOT NULL,
USER_CODE VARCHAR(20) NOT NULL,
CREATED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED_BY VARCHAR(20) NOT NULL,
PNR VARCHAR(25) NOT NULL,
AIRLINE_CODE VARCHAR(2) NOT NULL,
SUPPLIER VARCHAR(3) NOT NULL,
SUPPLIER_REF VARCHAR(50) NOT NULL,
QUOTED DECIMAL(18,2),
QUOTED_COST DECIMAL(18,2),
QUOTED_ADDITIONAL DECIMAL(18,2),
SUP_COST DECIMAL(18,2),
NET_COST DECIMAL(18,2),
NET_REMIT DECIMAL(18,2),
CHARGED DECIMAL(18,2),
REVENUE DECIMAL(18,2),
UNDER_CHARGE DECIMAL(18,2),
OVER_CHARGE DECIMAL(18,2),
MARKUP DECIMAL(18,2),
PROMOTION DECIMAL(18,2),
ADJUSTMENT DECIMAL(18,2),
CCFEE DECIMAL(18,2),
CUSTOMER_FOP VARCHAR(3),
SUPPLIER_FOP VARCHAR(3),
TRANS_INFO VARCHAR(1500),
REMARKS VARCHAR(1500),
PAX INT,
ADULT	INT,
CHILD	INT,
INFANT	INT,

JOURNEY_TYPE VARCHAR(3),
ORIGIN VARCHAR(3),
DESTINATION VARCHAR(3),
ONWARD_DATE TIMESTAMPTZ,
RETURN_DATE TIMESTAMPTZ,
RETURN_DATE1 TIMESTAMPTZ,
RETURN_DATE2 TIMESTAMPTZ,
RETURN_DATE3 TIMESTAMPTZ,
ITINERARY VARCHAR(100),
MULTICITY_ITINERARY VARCHAR(100),
CABIN VARCHAR(1),
BKG_CLASS VARCHAR(50),

ANCILLARY_TYPE VARCHAR(3),

CONSTRAINT ATD_PK PRIMARY KEY (ID),
CONSTRAINT ATD_UN UNIQUE (AIR_TRANS_DTL_ID),
CONSTRAINT ATD_TI_FK FOREIGN KEY(AIR_TRANS_ID) REFERENCES AIR_TRANS_HDR(AIR_TRANS_ID),
CONSTRAINT ATD_UC_FK FOREIGN KEY(USER_CODE) REFERENCES M_USER(USER_CODE),
CONSTRAINT ATD_MB_FK FOREIGN KEY(MODIFIED_BY) REFERENCES M_USER(USER_CODE)
);

CREATE INDEX ATD_IDX ON AIR_TRANS_DTL(AIR_TRANS_ID,AIR_TRANS_DTL_ID,PNR,USER_CODE,CREATED,BOOKING_TYPE,TRANS_TYPE,TRANS_STATUS,SUPPLIER);


CREATE TABLE AIR_FOP_COLLECTED(
ID BIGSERIAL NOT NULL,
AIR_TRANS_ID VARCHAR(12) NOT NULL,
AIR_FC_ID VARCHAR(20) NOT NULL,
USER_CODE VARCHAR(20) NOT NULL,
CREATED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED_BY VARCHAR(20) NOT NULL,
FOP_TYPE VARCHAR(3) NOT NULL,
FOP_STATUS VARCHAR(3) NOT NULL,
AUTH_AMOUNT DECIMAL(18,2) NOT NULL,
SETTLED_AMOUNT DECIMAL(18,2) NOT NULL,
CCFEE DECIMAL(18,2),
FIRSTEIGHT VARCHAR(8),
LASTFOUR VARCHAR(4),
CCINFO VARCHAR(500),
CCNO VARCHAR(100),
CCCODE VARCHAR(2),
CCEXP VARCHAR(5),
CCHOLDER_NAME VARCHAR(100),
CCBANK VARCHAR(250),
CONSIDER_AMT BIT DEFAULT '1' NOT NULL,
CONSTRAINT AFC_PK PRIMARY KEY (ID),
CONSTRAINT AFC_UN UNIQUE (AIR_FC_ID),
CONSTRAINT AFC_TI_FK FOREIGN KEY(AIR_TRANS_ID) REFERENCES AIR_TRANS_HDR(AIR_TRANS_ID),
CONSTRAINT AFC_UC_FK FOREIGN KEY(USER_CODE) REFERENCES M_USER(USER_CODE),
CONSTRAINT AFC_MB_FK FOREIGN KEY(MODIFIED_BY) REFERENCES M_USER(USER_CODE)
);

CREATE INDEX AFC_IDX ON AIR_FOP_COLLECTED(AIR_TRANS_ID,AIR_FC_ID,USER_CODE,CREATED,FOP_TYPE,FOP_STATUS,CCNO);


CREATE TABLE AIR_FOP_PAID(
ID BIGSERIAL NOT NULL,
AIR_TRANS_ID VARCHAR(12) NOT NULL,
AIR_FP_ID VARCHAR(20) NOT NULL,
USER_CODE VARCHAR(20) NOT NULL,
CREATED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED_BY VARCHAR(20) NOT NULL,
FOP_TYPE VARCHAR(3) NOT NULL,
FOP_STATUS VARCHAR(3) NOT NULL,
AUTH_AMOUNT DECIMAL(18,2) NOT NULL,
SETTLED_AMOUNT DECIMAL(18,2) NOT NULL,
CCFEE DECIMAL(18,2),
FIRSTEIGHT VARCHAR(8),
LASTFOUR VARCHAR(4),
CCINFO VARCHAR(500),
CCNO VARCHAR(100),
CCCODE VARCHAR(2),
CCEXP VARCHAR(5),
CCHOLDER_NAME VARCHAR(100),
CCBANK VARCHAR(250),
CONSIDER_AMT BIT DEFAULT '1' NOT NULL,
CONSTRAINT AFP_PK PRIMARY KEY (ID),
CONSTRAINT AFP_UN UNIQUE (AIR_FP_ID),
CONSTRAINT AFP_TI_FK FOREIGN KEY(AIR_TRANS_ID) REFERENCES AIR_TRANS_HDR(AIR_TRANS_ID),
CONSTRAINT AFP_UC_FK FOREIGN KEY(USER_CODE) REFERENCES M_USER(USER_CODE),
CONSTRAINT AFP_MB_FK FOREIGN KEY(MODIFIED_BY) REFERENCES M_USER(USER_CODE)
);

CREATE INDEX AFP_IDX ON AIR_FOP_PAID(AIR_TRANS_ID,AIR_FP_ID,USER_CODE,CREATED,FOP_TYPE,FOP_STATUS,CCNO);


CREATE TABLE AIR_INFO(
ID BIGSERIAL NOT NULL,
AIR_TRANS_ID VARCHAR(12) NOT NULL,
AIR_TRANS_DTL_ID VARCHAR(20) NOT NULL,
AIR_ID VARCHAR(20) NOT NULL,
ORIGIN VARCHAR(3) NOT NULL,
DESTINATION VARCHAR(3) NOT NULL,
AIRLINE_CODE VARCHAR(2) NOT NULL,
DEPART_DATETIME TIMESTAMPTZ NOT NULL,
ARRIVAL_DATETIME TIMESTAMPTZ NOT NULL,
CABIN VARCHAR(1) NOT NULL,
BKG_CLASS VARCHAR(25) NOT NULL,
FLIGHTNO VARCHAR(10) NOT NULL,
SEATNO VARCHAR(25),
FARE DECIMAL(18,2),
YQ DECIMAL(18,2),
YR DECIMAL(18,2),
AIRLINE_PNR VARCHAR(25) NOT NULL,
DEPART_FLAG BIT DEFAULT '1' NOT NULL,
LEG_NO INT,
OP_AIRLINE VARCHAR(2),
MK_AIRLINE VARCHAR(2),
FARE_TYPE VARCHAR(3),
FAREBASISCODE VARCHAR(25),
TOURCODE VARCHAR(50),
FARE_INFO VARCHAR(500),
ENDORSEMENT VARCHAR(100),
ADDL_BAGGAGE VARCHAR(500),
CREATED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
CONSTRAINT AI_PK PRIMARY KEY (ID),
CONSTRAINT AI_UN UNIQUE (AIR_ID),
CONSTRAINT AI_TI_FK FOREIGN KEY(AIR_TRANS_ID) REFERENCES AIR_TRANS_HDR(AIR_TRANS_ID),
CONSTRAINT AI_TDI_FK FOREIGN KEY(AIR_TRANS_DTL_ID) REFERENCES AIR_TRANS_DTL(AIR_TRANS_DTL_ID)
);

CREATE INDEX AI_IDX ON AIR_INFO(AIR_TRANS_ID,AIR_TRANS_DTL_ID,AIR_ID,ORIGIN,DESTINATION,AIRLINE_CODE,DEPART_FLAG,DEPART_DATETIME,ARRIVAL_DATETIME);

CREATE TABLE AIR_PAX_INFO(
ID BIGSERIAL NOT NULL,
AIR_TRANS_ID VARCHAR(12) NOT NULL,
AIR_TRANS_DTL_ID VARCHAR(20) NOT NULL,
PAX_ID VARCHAR(20) NOT NULL,
FIRSTNAME VARCHAR(60) NOT NULL,
LASTNAME VARCHAR(60) NOT NULL,
MIDDLENAME VARCHAR(60),
GENDER VARCHAR(1) NOT NULL,
DOB DATE,
PASSPORT VARCHAR(50),
NATIONALITY VARCHAR(50),
NAMENO VARCHAR(5),
PAXTYPE VARCHAR(3) NOT NULL,
TRAVELPREFERENCENO VARCHAR(50),
CONSTRAINT API_PK PRIMARY KEY (ID),
CONSTRAINT API_UN UNIQUE (PAX_ID),
CONSTRAINT API_TI_FK FOREIGN KEY(AIR_TRANS_ID) REFERENCES AIR_TRANS_HDR(AIR_TRANS_ID),
CONSTRAINT API_TDI_FK FOREIGN KEY(AIR_TRANS_DTL_ID) REFERENCES AIR_TRANS_DTL(AIR_TRANS_DTL_ID)
);

CREATE INDEX API_IDX ON AIR_PAX_INFO(AIR_TRANS_ID,AIR_TRANS_DTL_ID,PAX_ID,LASTNAME,FIRSTNAME,PAXTYPE);


CREATE TABLE AIR_PAX_BKG_INFO(
ID BIGSERIAL NOT NULL,
AIR_TRANS_ID VARCHAR(12) NOT NULL,
AIR_TRANS_DTL_ID VARCHAR(20) NOT NULL,
PAX_ID VARCHAR(20) NOT NULL,
PAX_BKG_ID VARCHAR(20) NOT NULL,
PNR VARCHAR(20) NOT NULL,
AIRLINE_CODE VARCHAR(2) NOT NULL,
TICKETNO VARCHAR(10),
GDS VARCHAR(3),
FARETYPE VARCHAR(3),
FAREINFO VARCHAR(500),
ENDORSEMENT VARCHAR(100),
TOURCODE VARCHAR(50),
FAREBASIS VARCHAR(25),
ITINERARY VARCHAR(100),
ORGDEST VARCHAR(6),
MC_ORGDEST VARCHAR(50),
TICKETFARE DECIMAL(18,2),
BASEFARE DECIMAL(18,2),
TAX DECIMAL(18,2),
TAXBREAKUP VARCHAR(100),
COMM DECIMAL(18,2),
NETIATAAMT DECIMAL(18,2),
FOPCODE VARCHAR(3),
TRANS_TYPE VARCHAR(3),
TRANS_STATUS VARCHAR(3),
PENALITY DECIMAL(18,2),
COMM_ON_PENALITY DECIMAL(18,2),
ORIGTICKETNO VARCHAR(10),
ORIGBASE_FARE DECIMAL(18,2),
ORIGTAX DECIMAL(18,2),
ORIGCOMM DECIMAL(18,2),
ORIGFOPCODE VARCHAR(3),
TOTALFARE DECIMAL(18,2),
NETFARE DECIMAL(18,2),
MARKUP DECIMAL(18,2),
PROMOTION DECIMAL(18,2),
ADJUSTMENT DECIMAL(18,2),
CCFEE DECIMAL(18,2),
MISC DECIMAL(18,2),
EXFEE DECIMAL(18,2),
RFFEE DECIMAL(18,2),
RECALLFEE DECIMAL(18,2),
REMARKS VARCHAR(500),
CREATED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
CONSTRAINT APBI_PK PRIMARY KEY (ID),
CONSTRAINT APBI_UN UNIQUE (PAX_BKG_ID),
CONSTRAINT APBI_TI_FK FOREIGN KEY(AIR_TRANS_ID) REFERENCES AIR_TRANS_HDR(AIR_TRANS_ID),
CONSTRAINT APBI_TDI_FK FOREIGN KEY(AIR_TRANS_DTL_ID) REFERENCES AIR_TRANS_DTL(AIR_TRANS_DTL_ID),
CONSTRAINT APBI_PI_FK FOREIGN KEY(PAX_ID) REFERENCES AIR_PAX_INFO(PAX_ID)
);

CREATE INDEX APBI_IDX ON AIR_PAX_BKG_INFO(AIR_TRANS_ID,AIR_TRANS_DTL_ID,PAX_ID,PAX_BKG_ID,PNR,TICKETNO,TRANS_TYPE,TRANS_STATUS,FOPCODE);


CREATE TABLE LINK_AIR_INFO_PAX_BKG(
ID BIGSERIAL NOT NULL,
AIR_TRANS_ID VARCHAR(12) NOT NULL,
AIR_TRANS_DTL_ID VARCHAR(20) NOT NULL,
PAX_ID VARCHAR(20) NOT NULL,
PAX_BKG_ID VARCHAR(20) NOT NULL,
AIR_ID VARCHAR(20) NOT NULL,
CONSTRAINT LAPBI_PK PRIMARY KEY (ID),
CONSTRAINT LAPBI_UN UNIQUE (AIR_TRANS_ID,AIR_TRANS_DTL_ID,PAX_ID,PAX_BKG_ID,AIR_ID),
CONSTRAINT LAPBI_TI_FK FOREIGN KEY(AIR_TRANS_ID) REFERENCES AIR_TRANS_HDR(AIR_TRANS_ID),
CONSTRAINT LAPBI_TDI_FK FOREIGN KEY(AIR_TRANS_DTL_ID) REFERENCES AIR_TRANS_DTL(AIR_TRANS_DTL_ID),
CONSTRAINT LAPBI_PI_FK FOREIGN KEY(PAX_ID) REFERENCES AIR_PAX_INFO(PAX_ID),
CONSTRAINT LAPBI_PBI_FK FOREIGN KEY(PAX_BKG_ID) REFERENCES AIR_PAX_BKG_INFO(PAX_BKG_ID),
CONSTRAINT LAPBI_AI_FK FOREIGN KEY(AIR_ID) REFERENCES AIR_INFO(AIR_ID)
);

CREATE INDEX LAPBI_IDX ON LINK_AIR_INFO_PAX_BKG(AIR_TRANS_ID,AIR_TRANS_DTL_ID,PAX_ID,PAX_BKG_ID,AIR_ID);


CREATE TABLE AIR_PAX_TKT_INFO(
ID BIGSERIAL NOT NULL,
AIR_TRANS_ID VARCHAR(12) NOT NULL,
AIR_TRANS_DTL_ID VARCHAR(20) NOT NULL,
PAX_ID VARCHAR(20) NOT NULL,
PAX_TKT_ID VARCHAR(20) NOT NULL,
PNR VARCHAR(20) NOT NULL,
AIRLINE_CODE VARCHAR(2) NOT NULL,
TICKETNO VARCHAR(10) NOT NULL,
GDS VARCHAR(3),
FARETYPE VARCHAR(3),
FAREINFO VARCHAR(500),
ENDORSEMENT VARCHAR(100),
TOURCODE VARCHAR(50),
FAREBASIS VARCHAR(25),
ITINERARY VARCHAR(100),
ORGDEST VARCHAR(6),
MC_ORGDEST VARCHAR(50),
TICKETFARE DECIMAL(18,2),
BASEFARE DECIMAL(18,2),
TAX DECIMAL(18,2),
TAXBREAKUP VARCHAR(100),
COMM DECIMAL(18,2),
NETIATAAMT DECIMAL(18,2),
FOPCODE VARCHAR(3),
TRANS_TYPE VARCHAR(3),
TRANS_STATUS VARCHAR(3),
PENALITY DECIMAL(18,2),
COMM_ON_PENALITY DECIMAL(18,2),
ORIGTICKETNO VARCHAR(10),
ORIGBASE_FARE DECIMAL(18,2),
ORIGTAX DECIMAL(18,2),
ORIGCOMM DECIMAL(18,2),
ORIGFOPCODE VARCHAR(3),
TOTALFARE DECIMAL(18,2),
NETFARE DECIMAL(18,2),
MARKUP DECIMAL(18,2),
PROMOTION DECIMAL(18,2),
ADJUSTMENT DECIMAL(18,2),
CCFEE DECIMAL(18,2),
MISC DECIMAL(18,2),
EXFEE DECIMAL(18,2),
RFFEE DECIMAL(18,2),
RECALLFEE DECIMAL(18,2),
REMARKS VARCHAR(500),
CREATED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
CONSTRAINT APTI_PK PRIMARY KEY (ID),
CONSTRAINT APTI_UN UNIQUE (PAX_TKT_ID),
CONSTRAINT APTI_TI_FK FOREIGN KEY(AIR_TRANS_ID) REFERENCES AIR_TRANS_HDR(AIR_TRANS_ID),
CONSTRAINT APTI_TDI_FK FOREIGN KEY(AIR_TRANS_DTL_ID) REFERENCES AIR_TRANS_DTL(AIR_TRANS_DTL_ID),
CONSTRAINT APTI_PI_FK FOREIGN KEY(PAX_ID) REFERENCES AIR_PAX_INFO(PAX_ID),
CONSTRAINT APTI_PTI_FK FOREIGN KEY(PAX_TKT_ID) REFERENCES AIR_PAX_TKT_INFO(PAX_TKT_ID)
);

CREATE INDEX APTI_IDX ON AIR_PAX_TKT_INFO(AIR_TRANS_ID,AIR_TRANS_DTL_ID,PAX_ID,PAX_TKT_ID,PNR,TICKETNO,TRANS_TYPE,TRANS_STATUS,FOPCODE);


CREATE TABLE LINK_AIR_INFO_PAX_TKT(
ID BIGSERIAL NOT NULL,
AIR_TRANS_ID VARCHAR(12) NOT NULL,
AIR_TRANS_DTL_ID VARCHAR(20) NOT NULL,
PAX_ID VARCHAR(20) NOT NULL,
PAX_TKT_ID VARCHAR(20) NOT NULL,
AIR_ID VARCHAR(20) NOT NULL,
CONSTRAINT LAPTI_PK PRIMARY KEY (ID),
CONSTRAINT LAPTI_UN UNIQUE (AIR_TRANS_ID,AIR_TRANS_DTL_ID,PAX_ID,PAX_TKT_ID,AIR_ID),
CONSTRAINT LAPTI_TI_FK FOREIGN KEY(AIR_TRANS_ID) REFERENCES AIR_TRANS_HDR(AIR_TRANS_ID),
CONSTRAINT LAPTI_TDI_FK FOREIGN KEY(AIR_TRANS_DTL_ID) REFERENCES AIR_TRANS_DTL(AIR_TRANS_DTL_ID),
CONSTRAINT LAPTI_PI_FK FOREIGN KEY(PAX_ID) REFERENCES AIR_PAX_INFO(PAX_ID),
CONSTRAINT LAPTI_PTI_FK FOREIGN KEY(PAX_TKT_ID) REFERENCES AIR_PAX_TKT_INFO(PAX_TKT_ID),
CONSTRAINT LAPTI_AI_FK FOREIGN KEY(AIR_ID) REFERENCES AIR_INFO(AIR_ID)
);

CREATE INDEX LAPTI_IDX ON LINK_AIR_INFO_PAX_TKT(AIR_TRANS_ID,AIR_TRANS_DTL_ID,PAX_ID,PAX_TKT_ID,AIR_ID);



CREATE TABLE LNK_FC_TRNS_DTL_AIR_PAX(
ID BIGSERIAL NOT NULL,
AIR_TRANS_ID VARCHAR(12) NOT NULL,
AIR_TRANS_DTL_ID VARCHAR(20) NOT NULL,
PAX_ID VARCHAR(20) NOT NULL,
PAX_TKT_ID VARCHAR(20) NOT NULL,
AIR_FC_ID VARCHAR(20) NOT NULL,
AMOUNT DECIMAL(18,2) NOT NULL,
CONSIDER_AMT BIT DEFAULT '0' NOT NULL,
IS_ACTIVE BIT DEFAULT '1' NOT NULL,
CONSTRAINT LFCTDAP_PK PRIMARY KEY (ID),
CONSTRAINT LFCTDAP_UN UNIQUE (AIR_TRANS_ID,AIR_TRANS_DTL_ID,PAX_ID,PAX_TKT_ID,AIR_FC_ID),
CONSTRAINT LFCTDAP_TI_FK FOREIGN KEY(AIR_TRANS_ID) REFERENCES AIR_TRANS_HDR(AIR_TRANS_ID),
CONSTRAINT LFCTDAP_TDI_FK FOREIGN KEY(AIR_TRANS_DTL_ID) REFERENCES AIR_TRANS_DTL(AIR_TRANS_DTL_ID),
CONSTRAINT LFCTDAP_PI_FK FOREIGN KEY(PAX_ID) REFERENCES AIR_PAX_INFO(PAX_ID),
CONSTRAINT LFCTDAP_PTI_FK FOREIGN KEY(PAX_TKT_ID) REFERENCES AIR_PAX_TKT_INFO(PAX_TKT_ID),
CONSTRAINT LFCTDAP_FC_FK FOREIGN KEY(AIR_FC_ID) REFERENCES AIR_FOP_COLLECTED(AIR_FC_ID)
);

CREATE INDEX LFCTDAP_IDX ON LNK_FC_TRNS_DTL_AIR_PAX(AIR_TRANS_ID,AIR_TRANS_DTL_ID,PAX_ID,PAX_TKT_ID,AIR_FC_ID);

CREATE TABLE LNK_FP_TRNS_DTL_AIR_PAX(
ID BIGSERIAL NOT NULL,
AIR_TRANS_ID VARCHAR(12) NOT NULL,
AIR_TRANS_DTL_ID VARCHAR(20) NOT NULL,
PAX_ID VARCHAR(20) NOT NULL,
PAX_TKT_ID VARCHAR(20) NOT NULL,
AIR_FP_ID VARCHAR(20) NOT NULL,
AMOUNT DECIMAL(18,2) NOT NULL,
CONSIDER_AMT BIT DEFAULT '0' NOT NULL,
IS_ACTIVE BIT DEFAULT '1' NOT NULL,
CONSTRAINT LFPTDAP_PK PRIMARY KEY (ID),
CONSTRAINT LFPTDAP_UN UNIQUE (AIR_TRANS_ID,AIR_TRANS_DTL_ID,PAX_ID,PAX_TKT_ID,AIR_FP_ID),
CONSTRAINT LFPTDAP_TI_FK FOREIGN KEY(AIR_TRANS_ID) REFERENCES AIR_TRANS_HDR(AIR_TRANS_ID),
CONSTRAINT LFPTDAP_TDI_FK FOREIGN KEY(AIR_TRANS_DTL_ID) REFERENCES AIR_TRANS_DTL(AIR_TRANS_DTL_ID),
CONSTRAINT LFPTDAP_PI_FK FOREIGN KEY(PAX_ID) REFERENCES AIR_PAX_INFO(PAX_ID),
CONSTRAINT LFPTDAP_PTI_FK FOREIGN KEY(PAX_TKT_ID) REFERENCES AIR_PAX_TKT_INFO(PAX_TKT_ID),
CONSTRAINT LFPTDAP_FP_FK FOREIGN KEY(AIR_FP_ID) REFERENCES AIR_FOP_PAID(AIR_FP_ID)
);

CREATE INDEX LFPTDAP_IDX ON LNK_FP_TRNS_DTL_AIR_PAX(AIR_TRANS_ID,AIR_TRANS_DTL_ID,PAX_ID,PAX_TKT_ID,AIR_FP_ID);