SET search_path TO ardor;


CREATE TABLE STY_TRANS_HDR(
ID BIGSERIAL NOT NULL,
STY_TRANS_ID VARCHAR(12) NOT NULL,
USER_CODE VARCHAR(20) NOT NULL,
CREATED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED_BY VARCHAR(20) NOT NULL,
FIRSTNAME VARCHAR(60),
LASTNAME VARCHAR(60),
EMAIL VARCHAR(100) NOT NULL,
PHONE VARCHAR(100) NOT NULL,
ADDRESS VARCHAR(1000),
TRANS_STATUS VARCHAR(3) NOT NULL,
QUOTED DECIMAL(18,2),
QUOTED_COST DECIMAL(18,2),
QUOTED_ADDITIONAL DECIMAL(18,2),
SUP_COST DECIMAL(18,2),
NET_COST DECIMAL(18,2),
NET_REMIT DECIMAL(18,2),
CHARGED DECIMAL(18,2),
REVENUE DECIMAL(18,2),
UNDER_CHARGE DECIMAL(18,2),
OVER_CHARGE DECIMAL(18,2),
MARKUP DECIMAL(18,2),
PROMOTION DECIMAL(18,2),
ADJUSTMENT DECIMAL(18,2),
CCFEE DECIMAL(18,2),
CUSTOMER_FOP VARCHAR(3),
SUPPLIER_FOP VARCHAR(3),
PAX VARCHAR(100),
TRANS_INFO VARCHAR(1500),
REMARKS VARCHAR(1500),
TRANS_IP VARCHAR(30),
TRANS_COUNTRY_CODE VARCHAR(3),
CONSTRAINT STH_PK PRIMARY KEY (ID),
CONSTRAINT STH_UN UNIQUE (STY_TRANS_ID),
CONSTRAINT STH_UC_FK FOREIGN KEY(USER_CODE) REFERENCES M_USER(USER_CODE),
CONSTRAINT STH_MB_FK FOREIGN KEY(MODIFIED_BY) REFERENCES M_USER(USER_CODE)
);

CREATE INDEX STH_IDX ON STY_TRANS_HDR(STY_TRANS_ID,USER_CODE,CREATED,TRANS_STATUS,TRANS_COUNTRY_CODE,EMAIL,PHONE);


CREATE TABLE STY_TRANS_DTL(
ID BIGSERIAL NOT NULL,
STY_TRANS_ID VARCHAR(12) NOT NULL,
STY_TRANS_DTL_ID VARCHAR(20) NOT NULL,
BOOKING_TYPE VARCHAR(3) NOT NULL,
TRANS_TYPE VARCHAR(3) NOT NULL,
TRANS_STATUS VARCHAR(3) NOT NULL,
USER_CODE VARCHAR(20) NOT NULL,
CREATED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED_BY VARCHAR(20) NOT NULL,
PNR VARCHAR(25) NOT NULL,
SUPPLIER VARCHAR(3) NOT NULL,
SUPPLIER_REF VARCHAR(50),
QUOTED DECIMAL(18,2),
QUOTED_COST DECIMAL(18,2),
QUOTED_ADDITIONAL DECIMAL(18,2),
SUP_COST DECIMAL(18,2),
NET_COST DECIMAL(18,2),
NET_REMIT DECIMAL(18,2),
CHARGED DECIMAL(18,2),
REVENUE DECIMAL(18,2),
UNDER_CHARGE DECIMAL(18,2),
OVER_CHARGE DECIMAL(18,2),
MARKUP DECIMAL(18,2),
PROMOTION DECIMAL(18,2),
ADJUSTMENT DECIMAL(18,2),
CCFEE DECIMAL(18,2),
CUSTOMER_FOP VARCHAR(3),
SUPPLIER_FOP VARCHAR(3),
PAX INT,
ADULT	INT,
CHILD	INT,
INFANT	INT,

STAY_CODE VARCHAR(100),
STAY_NAME VARCHAR(500),
CATEGORY_CODE VARCHAR(25),
CATEGORY_NAME VARCHAR(50),
CITY_CODE VARCHAR(20),
CITY_NAME VARCHAR(100),
ZONE_CODE VARCHAR(15),
ZONE_NAME VARCHAR(100),
LATITUDE VARCHAR(20),
LONGITUDE VARCHAR(20),
ROOM_CODE VARCHAR(20),
ROOM_NAME VARCHAR(50),
ROOM_TYPE VARCHAR(50),
RATE_KEY VARCHAR(500),
RATE_CLASS VARCHAR(20),
RATE_TYPE VARCHAR(20),
STAY_NET DECIMAL(18,2),
PAYMENT_TYPE VARCHAR(10),
PACKAGING BIT,
BOARD_CODE VARCHAR(10),
BOARD_NAME VARCHAR(100),
STAY_CANCELLATION_AMOUNT DECIMAL(18,2),
STAY_CANCELLATION_FROM_DATE TIMESTAMPTZ,
STAY_TAXAMT DECIMAL(18,2),
STAY_TAX_INCLUDED BIT,
STAY_CURRENCY VARCHAR(3),
STAY_CLIENT_TAXAMT DECIMAL(18,2),
STAY_CLIENT_CURRENCY VARCHAR(3),
STAY_ALL_INCLUDED BIT,
STAY_ROOMS INT,
CHECKIN_DATE TIMESTAMPTZ,
CHECKOUT_DATE TIMESTAMPTZ,

ANCILLARY_TYPE VARCHAR(3),

CONSTRAINT STD_PK PRIMARY KEY (ID),
CONSTRAINT STD_UN UNIQUE (STY_TRANS_DTL_ID),
CONSTRAINT STD_TI_FK FOREIGN KEY(STY_TRANS_ID) REFERENCES STY_TRANS_HDR(STY_TRANS_ID),
CONSTRAINT STD_UC_FK FOREIGN KEY(USER_CODE) REFERENCES M_USER(USER_CODE),
CONSTRAINT STD_MB_FK FOREIGN KEY(MODIFIED_BY) REFERENCES M_USER(USER_CODE)
);

CREATE INDEX STD_IDX ON STY_TRANS_DTL(STY_TRANS_ID,STY_TRANS_DTL_ID,PNR,USER_CODE,CREATED,BOOKING_TYPE,TRANS_TYPE,TRANS_STATUS,SUPPLIER);


CREATE TABLE STY_FOP_COLLECTED(
ID BIGSERIAL NOT NULL,
STY_TRANS_ID VARCHAR(12) NOT NULL,
STY_FC_ID VARCHAR(20) NOT NULL,
USER_CODE VARCHAR(20) NOT NULL,
CREATED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED_BY VARCHAR(20) NOT NULL,
FOP_TYPE VARCHAR(3) NOT NULL,
FOP_STATUS VARCHAR(3) NOT NULL,
AUTH_AMOUNT DECIMAL(18,2) NOT NULL,
SETTLED_AMOUNT DECIMAL(18,2) NOT NULL,
CCFEE DECIMAL(18,2),
FIRSTEIGHT VARCHAR(8),
LASTFOUR VARCHAR(4),
CCINFO VARCHAR(500),
CCNO VARCHAR(100),
CCCODE VARCHAR(2),
CCEXP VARCHAR(5),
CCHOLDER_NAME VARCHAR(100),
CCBANK VARCHAR(250),
CONSIDER_AMT BIT DEFAULT '1' NOT NULL,
CONSTRAINT SFC_PK PRIMARY KEY (ID),
CONSTRAINT SFC_UN UNIQUE (STY_FC_ID),
CONSTRAINT SFC_TI_FK FOREIGN KEY(STY_TRANS_ID) REFERENCES STY_TRANS_HDR(STY_TRANS_ID),
CONSTRAINT SFC_UC_FK FOREIGN KEY(USER_CODE) REFERENCES M_USER(USER_CODE),
CONSTRAINT SFC_MB_FK FOREIGN KEY(MODIFIED_BY) REFERENCES M_USER(USER_CODE)
);

CREATE INDEX SFC_IDX ON STY_FOP_COLLECTED(STY_TRANS_ID,STY_FC_ID,USER_CODE,CREATED,FOP_TYPE,FOP_STATUS,CCNO);


CREATE TABLE STY_FOP_PAID(
ID BIGSERIAL NOT NULL,
STY_TRANS_ID VARCHAR(12) NOT NULL,
STY_FP_ID VARCHAR(20) NOT NULL,
USER_CODE VARCHAR(20) NOT NULL,
CREATED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED TIMESTAMPTZ DEFAULT TRANSACTION_TIMESTAMP() NOT NULL,
MODIFIED_BY VARCHAR(20) NOT NULL,
FOP_TYPE VARCHAR(3) NOT NULL,
FOP_STATUS VARCHAR(3) NOT NULL,
AUTH_AMOUNT DECIMAL(18,2) NOT NULL,
SETTLED_AMOUNT DECIMAL(18,2) NOT NULL,
CCFEE DECIMAL(18,2),
FIRSTEIGHT VARCHAR(8),
LASTFOUR VARCHAR(4),
CCINFO VARCHAR(500),
CCNO VARCHAR(100),
CCCODE VARCHAR(2),
CCEXP VARCHAR(5),
CCHOLDER_NAME VARCHAR(100),
CCBANK VARCHAR(250),
CONSIDER_AMT BIT DEFAULT '1' NOT NULL,
CONSTRAINT SFP_PK PRIMARY KEY (ID),
CONSTRAINT SFP_UN UNIQUE (STY_FP_ID),
CONSTRAINT SFP_TI_FK FOREIGN KEY(STY_TRANS_ID) REFERENCES STY_TRANS_HDR(STY_TRANS_ID),
CONSTRAINT SFP_UC_FK FOREIGN KEY(USER_CODE) REFERENCES M_USER(USER_CODE),
CONSTRAINT SFP_MB_FK FOREIGN KEY(MODIFIED_BY) REFERENCES M_USER(USER_CODE)
);

CREATE INDEX SFP_IDX ON STY_FOP_PAID(STY_TRANS_ID,STY_FP_ID,USER_CODE,CREATED,FOP_TYPE,FOP_STATUS,CCNO);



CREATE TABLE STY_PAX_INFO(
ID BIGSERIAL NOT NULL,
STY_TRANS_ID VARCHAR(12) NOT NULL,
STY_TRANS_DTL_ID VARCHAR(20) NOT NULL,
PAX_ID VARCHAR(20) NOT NULL,
FIRSTNAME VARCHAR(60) NOT NULL,
LASTNAME VARCHAR(60) NOT NULL,
MIDDLENAME VARCHAR(60),
GENDER VARCHAR(1) NOT NULL,
DOB DATE,
PASSPORT VARCHAR(50),
NATIONALITY VARCHAR(50),
NAMENO VARCHAR(5),
PAXTYPE VARCHAR(3) NOT NULL,
TRAVELPREFERENCENO VARCHAR(50),
CONSTRAINT SPI_PK PRIMARY KEY (ID),
CONSTRAINT SPI_UN UNIQUE (PAX_ID),
CONSTRAINT SPI_TI_FK FOREIGN KEY(STY_TRANS_ID) REFERENCES STY_TRANS_HDR(STY_TRANS_ID),
CONSTRAINT SPI_TDI_FK FOREIGN KEY(STY_TRANS_DTL_ID) REFERENCES STY_TRANS_DTL(STY_TRANS_DTL_ID)
);

CREATE INDEX SPI_IDX ON STY_PAX_INFO(STY_TRANS_ID,STY_TRANS_DTL_ID,PAX_ID,LASTNAME,FIRSTNAME,PAXTYPE);

CREATE TABLE LNK_FC_TRNS_DTL_STAY(
ID BIGSERIAL NOT NULL,
STY_TRANS_ID VARCHAR(12) NOT NULL,
STY_TRANS_DTL_ID VARCHAR(20) NOT NULL,
STY_FC_ID VARCHAR(20) NOT NULL,
AMOUNT DECIMAL(18,2) NOT NULL,
CONSIDER_AMT BIT DEFAULT '0' NOT NULL,
IS_ACTIVE BIT DEFAULT '1' NOT NULL,
CONSTRAINT LFCTDS_PK PRIMARY KEY (ID),
CONSTRAINT LFCTDS_UN UNIQUE (STY_TRANS_ID,STY_TRANS_DTL_ID,STY_FC_ID),
CONSTRAINT LFCTDS_TI_FK FOREIGN KEY(STY_TRANS_ID) REFERENCES STY_TRANS_HDR(STY_TRANS_ID),
CONSTRAINT LFCTDS_TDI_FK FOREIGN KEY(STY_TRANS_DTL_ID) REFERENCES STY_TRANS_DTL(STY_TRANS_DTL_ID),
CONSTRAINT LFCTDS_FC_FK FOREIGN KEY(STY_FC_ID) REFERENCES STY_FOP_COLLECTED(STY_FC_ID)
);

CREATE INDEX LFCTDS_IDX ON LNK_FC_TRNS_DTL_STAY(STY_TRANS_ID,STY_TRANS_DTL_ID,STY_FC_ID);

CREATE TABLE LNK_FP_TRNS_DTL_STAY(
ID BIGSERIAL NOT NULL,
STY_TRANS_ID VARCHAR(12) NOT NULL,
STY_TRANS_DTL_ID VARCHAR(20) NOT NULL,
STY_FP_ID VARCHAR(20) NOT NULL,
AMOUNT DECIMAL(18,2) NOT NULL,
CONSIDER_AMT BIT DEFAULT '0' NOT NULL,
IS_ACTIVE BIT DEFAULT '1' NOT NULL,
CONSTRAINT LFPTDS_PK PRIMARY KEY (ID),
CONSTRAINT LFPTDS_UN UNIQUE (STY_TRANS_ID,STY_TRANS_DTL_ID,STY_FP_ID),
CONSTRAINT LFPTDS_TI_FK FOREIGN KEY(STY_TRANS_ID) REFERENCES STY_TRANS_HDR(STY_TRANS_ID),
CONSTRAINT LFPTDS_TDI_FK FOREIGN KEY(STY_TRANS_DTL_ID) REFERENCES STY_TRANS_DTL(STY_TRANS_DTL_ID),
CONSTRAINT LFPTDS_FP_FK FOREIGN KEY(STY_FP_ID) REFERENCES STY_FOP_PAID(STY_FP_ID)
);

CREATE INDEX LFPTDS_IDX ON LNK_FP_TRNS_DTL_STAY(STY_TRANS_ID,STY_TRANS_DTL_ID,STY_FP_ID);
